Introduce --version flag

diff --git a/addons/cilium/enable b/addons/cilium/enable
--- a/addons/cilium/enable
+++ b/addons/cilium/enable
@@ -6,6 +6,27 @@ source $SNAP/actions/common/utils.sh
 
 "$SNAP/microk8s-enable.wrapper" helm3
 
+CILIUM_VERSION=""
+OFFLINE_MODE="False"
+
+# Parse command-line arguments
+while [ "$#" -gt 0 ]; do
+  case "$1" in
+    --version)
+      CILIUM_VERSION="$2"
+      shift 2
+      ;;
+    --offline)
+      OFFLINE_MODE=True
+      shift
+      ;;
+    *)
+      echo "Invalid option: $1" >&2
+      exit 1
+      ;;
+  esac
+done
+
 echo "Ensure kube-apiserver --allow-privileged=true flag"
 if ! grep -qE -- "--allow-privileged=true" "$SNAP_DATA/args/kube-apiserver"; then
   echo "Adding kube-apiserver --allow-privileged=true flag"
@@ -39,7 +60,6 @@ fi
 echo "Enabling Cilium"
 
 # Cilium Supports Arm beginning v1.11.12 and greater
-read -ra CILIUM_VERSION <<< "$1"
 if [ -z "$CILIUM_VERSION" ]; then
   CILIUM_VERSION="v1.13.4"
 fi
@@ -97,7 +117,7 @@ else
   "$SNAP/microk8s-kubectl.wrapper" -n $NAMESPACE rollout status ds/cilium
 
   # Skip installing the Cilium CLI binary if the cluster is in offline mode
-  if [[ "$*" != *"--offline"* ]]; then
+  if [[ "$OFFLINE_MODE" == False ]]; then
     # Fetch the Cilium CLI binary and install
     ARCH=$(arch)
     SCRIPT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
@@ -125,4 +145,7 @@ else
   echo "In offline mode, the Cilium CLI binary will not be installed."
   echo "You can enable offline mode with:"
   echo "  sudo microk8s enable cilium --offline"
+  echo
+  echo "You can also specify a Cilium version with:"
+  echo "  sudo microk8s enable cilium --version <version>"
 fi
